### ISSUE TITLE
Repo code

### ISSUE THREAD

**Issue by sergioamm17** [pictos/MFCC#1]
I saw that your repo is not up-to-date according to the video on Gerald Versluis channel on the Xam Expert Day.
Could you please update the repository just to have a good example of creating native views on android and iOS using a handler?

**Comment by pictos** [comment]
@sergioamm17 this repo isn't for the Xam Expert Day event. This is for the Monkey Fest event

**Comment by sergioamm17** [comment]
Is the repo for Xam Expert Day available to check out the example? 
I've been looking at a lot of examples and this project is the only one that fits what I need. Pls.

**Comment by pictos** [comment]
@sergioamm17 , I believe is this one

- https://github.com/pictos/XamExpertDay/tree/pj-finished

**Comment by sergioamm17** [comment]
Thanks for answering.

The link throws me a 404 error, Is the repo private?

**Comment by pictos** [comment]
@sergioamm17 fixed

**Comment by sergioamm17** [comment]
Now it's working
Thank you so much, have a great day!

**Comment by pictos** [comment]
You too

**Comment by sergioamm17** [comment]
By the way, one more question...
Have you ever tried to load a xib or swift file for iOS specific code, instead of creating the view programmatically? Is that possible with MAUI?

**Comment by pictos** [comment]
Never tried it... Not sure if that can be done via native bindings... I suggest you open a discussion in the .NET MAUI repo

**Comment by sergioamm17** [comment]
Thx, I'm going to do that...
